spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true            
    datasource:  
        driver-class-name: com.mysql.jdbc.Driver  
        url: jdbc:mysql://127.0.0.1:3306/springboot 
        username: root
        password: 123456
    data:
      mongodb:
        uri: mongodb://192.168.1.99:20000/springboot-db
    redis:
      host: 192.168.1.130
      port: 6379
      database: 1 
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      timeout: 0
     
mybatis:
    type-aliases-package: ghost.springboot.entity
    mapper-locations: classpath:mapper/*Mapper.xml